project_id = "icjrpwccarkbkrvrkhdv"

[functions.create-bulk-users]
verify_jwt = true

[functions.create-user]
verify_jwt = true

[functions.delete-user]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.update-user]
verify_jwt = true
